
apiVersion: apps/v1
kind: Deployment
metadata:
  name: formservice01
spec:
  selector:
    matchLabels:
      name: formservice01
  template:
    metadata:
      labels:
        name: formservice01
    spec:
      containers:
        - name: app
          image: 306881650362.dkr.ecr.us-gov-west-1.amazonaws.com/faas-sandb/microservice:latest
          ports:
            - containerPort: 818